# Generated by Django 5.2 on 2025-05-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_salary_visible', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='media/company_logos/')),
                ('company_website', models.URLField(blank=True, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('experience_level', models.CharField(blank=True, choices=[('Internship', 'Internship'), ('Junior', 'Junior'), ('Mid-level', 'Mid-level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Executive', 'Executive')], max_length=20, null=True)),
                ('contract_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Contractor', 'Contractor'), ('Internship', 'Internship'), ('Freelance', 'Freelance'), ('Temporary', 'Temporary'), ('Volunteer', 'Volunteer'), ('Other', 'Other')], max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('IT', 'IT'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('HR', 'HR'), ('Sales', 'Sales'), ('Customer Service', 'Customer Service'), ('Operations', 'Operations'), ('Legal', 'Legal'), ('Engineering', 'Engineering'), ('Design', 'Design'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Construction', 'Construction'), ('Manufacturing', 'Manufacturing'), ('Hospitality', 'Hospitality'), ('Transportation', 'Transportation'), ('Real Estate', 'Real Estate'), ('Telecommunications', 'Telecommunications'), ('Media', 'Media'), ('Entertainment', 'Entertainment'), ('Retail', 'Retail'), ('Non-profit', 'Non-profit'), ('Government', 'Government'), ('Agriculture', 'Agriculture'), ('Energy', 'Energy'), ('Pharmaceutical', 'Pharmaceutical'), ('Automotive', 'Automotive'), ('Aerospace', 'Aerospace'), ('Biotechnology', 'Biotechnology'), ('Chemicals', 'Chemicals'), ('Textiles', 'Textiles'), ('Food and Beverage', 'Food and Beverage'), ('Sports', 'Sports'), ('Fashion', 'Fashion'), ('Art and Culture', 'Art and Culture'), ('Travel and Tourism', 'Travel and Tourism'), ('Security', 'Security'), ('Insurance', 'Insurance'), ('Other', 'Other')], max_length=50, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('application_link', models.URLField(blank=True, null=True)),
                ('email_to_apply', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_to_apply', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
